apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: sample-nats
  namespace: demo
spec:
  clientConfig:
    service:
      name: sample-nats
      namespace: demo
      port: 4222
      scheme: nats
  type: nats.io/nats
  version: 2.6.1