apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deploy-demo
  namespace: demo
spec:
  runtimeSettings:
    container:
      securityContext:
        runAsGroup: 0
  paused: true
  repository:
    name: nfs-repo
  schedule: "*/3 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: sample-deployment
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
