apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stash-restore-job
subjects:
- kind: ServiceAccount
  name: stash-restore-etcd-restore-0
  namespace: demo
