apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-data
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-restored
  name: sample-deployment-restored
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-restored
  template:
    metadata:
      labels:
        app: busybox-restored
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: source-data