apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: gcs-repo-1
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: demo/deployment
    storageSecretName: gcs-secret
