apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: demo
spec:
  backend:
    s3:
      region: us-east-1
      endpoint: s3.amazonaws.com
      bucket: stash-testing
      prefix: /demo/deployment
    storageSecretName: s3-secret
