apiVersion: v1
kind: Service
metadata:
  name: headless
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 0
  selector:
    app: stash-demo-2
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stash-demo-2
  namespace: demo
  labels:
    app: stash-demo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo-2
  serviceName: headless
  template:
    metadata:
      labels:
        app: stash-demo-2
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c","echo $(POD_NAME) > /source/data/data.txt && sleep 3000"]
        env:
        - name:  POD_NAME
          valueFrom:
            fieldRef:
              fieldPath:  metadata.name
        volumeMounts:
        - name: source-data-2
          mountPath: "/source/data"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 200Mi
          requests:
            cpu: 500m
            ephemeral-storage: 200Mi
            memory: 200Mi

  volumeClaimTemplates:
  - metadata:
      name: source-data-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "csi-standard"
      resources:
        requests:
          storage: 200Mi