apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-xtradb-backup
  namespace: demo
spec:
  task:
    name: perconaxtradb-backup-5.7
  schedule: "*/5 * * * *"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-xtradb
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
