apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-xtradb-restore
  namespace: demo
spec:
  task:
    name: perconaxtradb-restore-5.7
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-xtradb-restored
  rules:
  - snapshots: ["latest"]
