apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: restored-mgo-sh
  namespace: demo
spec:
  clientConfig:
    service:
      name: restored-mgo-sh
      port: 27017
      scheme: mongodb
      namespace: fact
  parameters:
    apiVersion: config.kubedb.com/v1alpha1
    configServer: cnfRepSet/restored-mgo-sh-configsvr-0.restored-mgo-sh-configsvr-pods.fact.svc:27017,restored-mgo-sh-configsvr-1.restored-mgo-sh-configsvr-pods.fact.svc:27017,restored-mgo-sh-configsvr-2.restored-mgo-sh-configsvr-pods.fact.svc:27017
    kind: MongoConfiguration
    replicaSets:
      host-0: shard0/restored-mgo-sh-shard0-0.restored-mgo-sh-shard0-pods.fact.svc:27017,restored-mgo-sh-shard0-1.restored-mgo-sh-shard0-pods.fact.svc:27017,restored-mgo-sh-shard0-2.restored-mgo-sh-shard0-pods.fact.svc:27017
      host-1: shard1/restored-mgo-sh-shard1-0.restored-mgo-sh-shard1-pods.fact.svc:27017,restored-mgo-sh-shard1-1.restored-mgo-sh-shard1-pods.fact.svc:27017,restored-mgo-sh-shard1-2.restored-mgo-sh-shard1-pods.fact.svc:27017
      host-2: shard2/restored-mgo-sh-shard2-0.restored-mgo-sh-shard2-pods.fact.svc:27017,restored-mgo-sh-shard2-1.restored-mgo-sh-shard2-pods.fact.svc:27017,restored-mgo-sh-shard2-2.restored-mgo-sh-shard2-pods.fact.svc:27017
    stash:
      addon:
        backupTask:
          name: mongodb-backup-4.4.6
        restoreTask:
          name: mongodb-restore-4.4.6
  secret:
    name: restored-mgo-sh-auth
  type: kubedb.com/mongodb
  version: 4.4.6
