apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sample-mg-rs
  namespace: demo
spec:
  version: "6.0.5"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
