apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sample-mg-restored
  namespace: demo
spec:
  version: "6.0.5"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  init:
    waitForInitialRestore: true
  terminationPolicy: WipeOut
