apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: sample-mg-sh
  namespace: demo
spec:
  init:
    waitForInitialRestore: true
  version: "6.0.5"
  shardTopology:
    configServer:
      replicas: 2
      storage:
        resources:
          requests:
            storage: 1Gi
    mongos:
      replicas: 2
    shard:
      replicas: 2
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
  terminationPolicy: WipeOut
