apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: restored-mgo-sh
  namespace: demo
spec:
  version: "4.4.6"
  shardTopology:
    configServer:
      replicas: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 2
    shard:
      replicas: 2
      shards: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  init:
    waitForInitialRestore: true
  terminationPolicy: WipeOut
