apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-mysql-backup
  namespace: demo
spec:
  # task:
  #   name: mysql-backup-8.0.21
  #   params:
  #   - name: args
  #     value: --set-gtid-purged=OFF

  task:
    name: mysql-backup-5.7.25
    params:
    # - name: args
    #   value: --set-gtid-purged=OFF
  paused: true
  schedule: "*/3 * * * *"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mysql
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
