apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-mysql-backup
  namespace: demo
spec:
  schedule: "*/5 * * * *"
  repository:
    name: gcs-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mysql
  # hooks:
  #   preBackup:
  #     exec:
  #       command:
  #         - /bin/sh
  #         - -c
  #         - sleep 3000
  #     containerName: mysql # KubeDB uses "mysql" name for MySQL database container. If you haven't used KubeDB, change this according to your setup.
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
