apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: sample-mysql-restored
  namespace: demo
spec:
  init:
    waitForInitialRestore: true
  version: "8.1.0"
  replicas: 3
  topology:
    mode: GroupReplication
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut