apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deploy-demo
  namespace: demo
spec:
  timeOut: 100000000000
  repository:
    name: gcs-repo
  schedule: "*/4 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths: 
    - /source/data
  hooks:
    preBackup:
      exec:
        command:
          - /bin/sh
          - -c
          - sleep 600
      containerName: busybox
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true